# Generated by Django 4.1 on 2022-08-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
